In [4]:
path = os.getcwd()
print("Current Directory", path)
 
parent_directory = os.path.dirname(path)
print("Parent Directory", parent_directory)

data_directory = parent_directory + '\data'
print("Data Directory", data_directory)

Current Directory c:\Users\elmha\OneDrive - Universidad de Chile\GitHub\Sistema_Experto_APP_v1\notebooks\PyCaret
Parent Directory c:\Users\elmha\OneDrive - Universidad de Chile\GitHub\Sistema_Experto_APP_v1\notebooks
Data Directory c:\Users\elmha\OneDrive - Universidad de Chile\GitHub\Sistema_Experto_APP_v1\notebooks\data

In [3]:
import os
APP_PATH = os.path.join(ROOT_DIR, 'app.py')  # requires `import os`

NameError: name 'ROOT_DIR' is not defined

In [2]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
from src.data.load_dataset import load_data

ModuleNotFoundError: No module named 'src'

In [17]:
local_path = '.\data\Horcon-etiquetado_con_1_etiqueta.csv'
import pytz
import pandas as pd

def load_data(path):
    '''
    ARGS: path to the local .csv file
    Load data and search for the Date_Time column to index the dataframe by a datetime value.

    '''
    data = pd.read_csv(path, sep=';')
    data['Date_Time'] = pd.to_datetime(data['Date_Time'])
    data.set_index('Date_Time', inplace=True)
    chile=pytz.timezone('Chile/Continental')
    data.index = data.index.tz_localize(pytz.utc).tz_convert(chile)
    return data

In [ ]:
path = os.getcwd()
print("Current Directory", path)
 
parent_directory = os.path.dirname(path)
print("Parent Directory", parent_directory)

data_directory = parent_directory + '\data'
print("Data Directory", data_directory)

Current Directory c:\Users\elmha\OneDrive - Universidad de Chile\GitHub\Sistema_Experto_APP_v1\notebooks
Parent Directory c:\Users\elmha\OneDrive - Universidad de Chile\GitHub\Sistema_Experto_APP_v1
Data Directory c:\Users\elmha\OneDrive - Universidad de Chile\GitHub\Sistema_Experto_APP_v1\data

In [18]:
datas = load_data(local_path)
datas.head()

,Pression [cm H2O],Temperatura [°C],EC [µs/cm],etiqueta conjunta
Date_Time,,,,
2013-02-03 10:00:00-03:00,981.5,17.81,257,1
2013-02-03 11:00:00-03:00,871.1,17.86,9,1
2013-02-03 12:00:00-03:00,870.7,17.80,9,1
2013-02-03 13:00:00-03:00,1025.5,17.71,256,1
2013-02-03 14:00:00-03:00,870.3,17.84,9,1

In [43]:
from pycaret.classification import *

s = setup(datas, target = 'etiqueta conjunta', session_id = 123, silent = True, use_gpu = True)

In [20]:
# model training and selection
best = compare_models(sort='F1')
# con se_venv

In [21]:
last = pull()
last

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
catboost,CatBoost Classifier,0.9662,0.9860,0.7761,0.9065,0.8360,0.8173,0.8205,6.240
lightgbm,Light Gradient Boosting Machine,0.9658,0.9845,0.7672,0.9114,0.8329,0.8140,0.8179,1.304
xgboost,Extreme Gradient Boosting,0.9644,0.9855,0.7724,0.8933,0.8280,0.8082,0.8112,0.497
rf,Random Forest Classifier,0.9641,0.9788,0.7576,0.9048,0.8245,0.8047,0.8088,0.791
et,Extra Trees Classifier,0.9619,0.9744,0.7304,0.9091,0.8098,0.7889,0.7949,0.833
dt,Decision Tree Classifier,0.9536,0.8847,0.7956,0.7890,0.7922,0.7661,0.7662,0.057
gbc,Gradient Boosting Classifier,0.9500,0.9619,0.5846,0.9460,0.7221,0.6964,0.7211,1.319
knn,K Neighbors Classifier,0.9342,0.8461,0.5194,0.8243,0.6367,0.6026,0.6223,1.109
ada,Ada Boost Classifier,0.9323,0.8960,0.4467,0.8898,0.5943,0.5618,0.6020,0.519
qda,Quadratic Discriminant Analysis,0.9220,0.8040,0.3541,0.8658,0.5020,0.4677,0.5235,0.024
lda,Linear Discriminant Analysis,0.9247,0.6902,0.3228,1.0000,0.4873,0.4581,0.5450,0.025
ridge,Ridge Classifier,0.9246,0.0000,0.3224,1.0000,0.4869,0.4576,0.5447,0.017
lr,Logistic Regression,0.9246,0.7272,0.3220,1.0000,0.4865,0.4572,0.5443,0.092
nb,Naive Bayes,0.9193,0.7897,0.3357,0.8466,0.4800,0.4451,0.5019,0.017
svm,SVM - Linear Kernel,0.6767,0.0000,0.5246,0.6820,0.3897,0.3062,0.3595,0.217
dummy,Dummy Classifier,0.8888,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.014

In [22]:
from pycaret.classification import *

s = setup(datas, target = 'etiqueta conjunta', session_id = 123, silent = True, use_gpu = True, fold_strategy='timeseries')

In [23]:
# model training and selection
best = compare_models(sort='F1')

In [24]:
ts_last=pull()
ts_last

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
catboost,CatBoost Classifier,0.9628,0.9813,0.7508,0.8954,0.8162,0.7957,0.7998,4.682
lightgbm,Light Gradient Boosting Machine,0.9619,0.9790,0.7556,0.8827,0.8138,0.7927,0.7959,1.195
xgboost,Extreme Gradient Boosting,0.9616,0.9797,0.7546,0.8805,0.8120,0.7908,0.7941,0.399
rf,Random Forest Classifier,0.9613,0.9737,0.7291,0.9005,0.8050,0.7838,0.7896,0.514
et,Extra Trees Classifier,0.9588,0.9698,0.7042,0.9009,0.7899,0.7675,0.7750,0.588
dt,Decision Tree Classifier,0.9481,0.8748,0.7801,0.7581,0.7682,0.7391,0.7396,0.037
gbc,Gradient Boosting Classifier,0.9511,0.9573,0.5877,0.9498,0.7256,0.7004,0.7251,0.740
knn,K Neighbors Classifier,0.9338,0.8446,0.5036,0.8308,0.6265,0.5926,0.6153,0.104
ada,Ada Boost Classifier,0.9333,0.8906,0.4447,0.9012,0.5948,0.5630,0.6053,0.272
qda,Quadratic Discriminant Analysis,0.9238,0.8052,0.3605,0.8785,0.5103,0.4768,0.5333,0.014
lda,Linear Discriminant Analysis,0.9259,0.6945,0.3292,1.0000,0.4946,0.4655,0.5507,0.017
lr,Logistic Regression,0.9258,0.7255,0.3283,1.0000,0.4936,0.4646,0.5500,0.057
ridge,Ridge Classifier,0.9258,0.0000,0.3283,1.0000,0.4936,0.4646,0.5500,0.013
nb,Naive Bayes,0.9211,0.7925,0.3425,0.8596,0.4887,0.4545,0.5121,0.014
svm,SVM - Linear Kernel,0.9218,0.0000,0.3279,0.9479,0.4835,0.4512,0.5286,0.117
dummy,Dummy Classifier,0.8897,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.012

In [25]:
from pycaret.classification import *

s = setup(datas, target = 'etiqueta conjunta', session_id = 123, silent = True, use_gpu = True, fold_strategy='timeseries', data_split_shuffle = False)

In [26]:
# model training and selection
best_ts_sinshuffle = compare_models()

In [27]:
ts_last_s_shuffle = pull()
ts_last_s_shuffle

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
ridge,Ridge Classifier,0.9288,0.0000,0.5884,0.7021,0.5066,NaN,0.5305,0.014
lda,Linear Discriminant Analysis,0.9259,0.7630,0.6066,0.7020,0.5164,NaN,0.5395,0.018
lr,Logistic Regression,0.9095,0.8065,0.8004,0.7245,0.6412,NaN,0.6588,0.075
svm,SVM - Linear Kernel,0.9078,0.0000,0.7909,0.8015,0.6987,NaN,0.7062,0.087
nb,Naive Bayes,0.8931,0.8294,0.8004,0.6408,0.5685,NaN,0.5953,0.015
catboost,CatBoost Classifier,0.8783,0.8117,0.8004,0.6276,0.5558,0.5383,0.5755,4.680
rf,Random Forest Classifier,0.8759,0.8269,0.8004,0.5553,0.4999,0.4813,0.5279,0.544
xgboost,Extreme Gradient Boosting,0.8752,0.8003,0.7941,0.6263,0.5515,0.5339,0.5708,0.288
qda,Quadratic Discriminant Analysis,0.8722,0.7898,0.8004,0.7184,0.6325,NaN,0.6438,0.016
et,Extra Trees Classifier,0.8710,0.8291,0.8004,0.6192,0.5516,0.5339,0.5705,0.648
gbc,Gradient Boosting Classifier,0.8678,0.7827,0.7941,0.5925,0.5271,0.5065,0.5472,0.695
dummy,Dummy Classifier,0.8674,0.4500,0.1000,0.0015,0.0029,NaN,0.0000,0.009
knn,K Neighbors Classifier,0.8604,0.8147,0.8004,0.5150,0.4798,0.4667,0.5120,0.474
lightgbm,Light Gradient Boosting Machine,0.8589,0.8081,0.8004,0.6205,0.5511,0.5332,0.5683,0.996
dt,Decision Tree Classifier,0.8371,0.7847,0.7941,0.5143,0.4690,0.4480,0.4977,0.025
ada,Ada Boost Classifier,0.8348,0.8031,0.8004,0.5553,0.4933,0.4666,0.5157,0.293

#  PRUEBA DE AUTOML

Pruebas de AUTOML

In [ ]:
from pycaret.classification import *

s = setup(datas, target = 'etiqueta conjunta', session_id = 123, silent = True, use_gpu = True)

In [ ]:

# compare all baseline models and select top 5
top5 = compare_models(n_select = 5) 
# tune top 5 base models
tuned_top5 = [tune_model(i) for i in top5]
# ensemble top 5 tuned models
bagged_top5 = [ensemble_model(i) for i in tuned_top5]
# blend top 5 base models 
blender = blend_models(estimator_list = top5) 
# stack top 5 models
stacker = stack_models(estimator_list = top5[1:], meta_model = top5[0])
# select best model 
best = automl(optimize = 'Recall')

In [ ]:
best = compare_models(n_select=2)
c = pull()
c

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
lightgbm,Light Gradient Boosting Machine,0.9658,0.9845,0.7672,0.9114,0.8329,0.8140,0.8179,1.072
xgboost,Extreme Gradient Boosting,0.9644,0.9855,0.7724,0.8933,0.8280,0.8082,0.8112,0.443
rf,Random Forest Classifier,0.9641,0.9788,0.7576,0.9048,0.8245,0.8047,0.8088,0.937
et,Extra Trees Classifier,0.9619,0.9744,0.7304,0.9091,0.8098,0.7889,0.7949,1.071
dt,Decision Tree Classifier,0.9536,0.8847,0.7956,0.7890,0.7922,0.7661,0.7662,0.069
gbc,Gradient Boosting Classifier,0.9500,0.9619,0.5846,0.9460,0.7221,0.6964,0.7211,1.367
knn,K Neighbors Classifier,0.9342,0.8461,0.5194,0.8243,0.6367,0.6026,0.6223,0.723
ada,Ada Boost Classifier,0.9323,0.8960,0.4467,0.8898,0.5943,0.5618,0.6020,0.458
lda,Linear Discriminant Analysis,0.9247,0.6902,0.3228,1.0000,0.4873,0.4581,0.5450,0.031
lr,Logistic Regression,0.9246,0.7272,0.3220,1.0000,0.4865,0.4572,0.5443,0.113
ridge,Ridge Classifier,0.9246,0.0000,0.3224,1.0000,0.4869,0.4576,0.5447,0.021
qda,Quadratic Discriminant Analysis,0.9220,0.8040,0.3541,0.8658,0.5020,0.4677,0.5235,0.022
nb,Naive Bayes,0.9193,0.7897,0.3357,0.8466,0.4800,0.4451,0.5019,0.033
dummy,Dummy Classifier,0.8888,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.014
catboost,CatBoost Classifier,0.8696,0.8882,0.7001,0.8150,0.7529,0.7361,0.7389,6.539
svm,SVM - Linear Kernel,0.6767,0.0000,0.5246,0.6820,0.3897,0.3062,0.3595,0.252

In [ ]:
best_score_grid = pull()

best_score_grid

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
catboost,CatBoost Classifier,0.9662,0.9860,0.7761,0.9065,0.8360,0.8173,0.8205,7.590
lightgbm,Light Gradient Boosting Machine,0.9658,0.9845,0.7672,0.9114,0.8329,0.8140,0.8179,1.572
xgboost,Extreme Gradient Boosting,0.9644,0.9855,0.7724,0.8933,0.8280,0.8082,0.8112,0.526
rf,Random Forest Classifier,0.9641,0.9788,0.7576,0.9048,0.8245,0.8047,0.8088,0.976
et,Extra Trees Classifier,0.9619,0.9744,0.7304,0.9091,0.8098,0.7889,0.7949,1.061
dt,Decision Tree Classifier,0.9536,0.8847,0.7956,0.7890,0.7922,0.7661,0.7662,0.061
gbc,Gradient Boosting Classifier,0.9500,0.9619,0.5846,0.9460,0.7221,0.6964,0.7211,1.352
knn,K Neighbors Classifier,0.9342,0.8461,0.5194,0.8243,0.6367,0.6026,0.6223,0.174
ada,Ada Boost Classifier,0.9323,0.8960,0.4467,0.8898,0.5943,0.5618,0.6020,0.575
lda,Linear Discriminant Analysis,0.9247,0.6902,0.3228,1.0000,0.4873,0.4581,0.5450,0.025
lr,Logistic Regression,0.9246,0.7272,0.3220,1.0000,0.4865,0.4572,0.5443,0.085
ridge,Ridge Classifier,0.9246,0.0000,0.3224,1.0000,0.4869,0.4576,0.5447,0.019
qda,Quadratic Discriminant Analysis,0.9220,0.8040,0.3541,0.8658,0.5020,0.4677,0.5235,0.022
nb,Naive Bayes,0.9193,0.7897,0.3357,0.8466,0.4800,0.4451,0.5019,0.020
dummy,Dummy Classifier,0.8888,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.013
svm,SVM - Linear Kernel,0.6767,0.0000,0.5246,0.6820,0.3897,0.3062,0.3595,0.228

# Prueba de clasificación y luego detección de anomalías

In [28]:
from pycaret.classification import *

supervised = setup(datas, target = 'etiqueta conjunta', session_id = 123, silent = True, use_gpu = True)

In [29]:
# model training and selection
best_supervised = compare_models(sort='F1')
# con se_venv

In [30]:
score_grid_best_supervised = pull()
score_grid_best_supervised

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
catboost,CatBoost Classifier,0.9662,0.9860,0.7761,0.9065,0.8360,0.8173,0.8205,6.852
lightgbm,Light Gradient Boosting Machine,0.9658,0.9845,0.7672,0.9114,0.8329,0.8140,0.8179,1.019
xgboost,Extreme Gradient Boosting,0.9644,0.9855,0.7724,0.8933,0.8280,0.8082,0.8112,0.447
rf,Random Forest Classifier,0.9641,0.9788,0.7576,0.9048,0.8245,0.8047,0.8088,0.721
et,Extra Trees Classifier,0.9619,0.9744,0.7304,0.9091,0.8098,0.7889,0.7949,0.760
dt,Decision Tree Classifier,0.9536,0.8847,0.7956,0.7890,0.7922,0.7661,0.7662,0.064
gbc,Gradient Boosting Classifier,0.9500,0.9619,0.5846,0.9460,0.7221,0.6964,0.7211,1.298
knn,K Neighbors Classifier,0.9342,0.8461,0.5194,0.8243,0.6367,0.6026,0.6223,0.416
ada,Ada Boost Classifier,0.9323,0.8960,0.4467,0.8898,0.5943,0.5618,0.6020,0.434
qda,Quadratic Discriminant Analysis,0.9220,0.8040,0.3541,0.8658,0.5020,0.4677,0.5235,0.017
lda,Linear Discriminant Analysis,0.9247,0.6902,0.3228,1.0000,0.4873,0.4581,0.5450,0.023
ridge,Ridge Classifier,0.9246,0.0000,0.3224,1.0000,0.4869,0.4576,0.5447,0.017
lr,Logistic Regression,0.9246,0.7272,0.3220,1.0000,0.4865,0.4572,0.5443,0.096
nb,Naive Bayes,0.9193,0.7897,0.3357,0.8466,0.4800,0.4451,0.5019,0.018
svm,SVM - Linear Kernel,0.6767,0.0000,0.5246,0.6820,0.3897,0.3062,0.3595,0.227
dummy,Dummy Classifier,0.8888,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.011

In [33]:
datas.head()

,Pression [cm H2O],Temperatura [°C],EC [µs/cm],etiqueta conjunta
Date_Time,,,,
2013-02-03 10:00:00-03:00,981.5,17.81,257,1
2013-02-03 11:00:00-03:00,871.1,17.86,9,1
2013-02-03 12:00:00-03:00,870.7,17.80,9,1
2013-02-03 13:00:00-03:00,1025.5,17.71,256,1
2013-02-03 14:00:00-03:00,870.3,17.84,9,1

In [37]:
datas.drop(labels='etiqueta conjunta',axis=1).head()

                           Pression [cm H2O]  Temperatura [°C]  EC [µs/cm]
Date_Time
2013-02-03 10:00:00-03:00              981.5             17.81         257
2013-02-03 11:00:00-03:00              871.1             17.86           9
2013-02-03 12:00:00-03:00              870.7             17.80           9
2013-02-03 13:00:00-03:00             1025.5             17.71         256
2013-02-03 14:00:00-03:00              870.3             17.84           9

In [40]:
from pycaret.anomaly import *

# setup(datas, target = 'etiqueta conjunta', session_id = 123, silent = True, use_gpu = True)
anomaly_detection = setup(data = datas.drop(labels='etiqueta conjunta',axis=1),session_id=123, silent=True, profile=False, use_gpu=True, log_experiment = True, experiment_name='anomaly detection testing')

knn = create_model('knn')

evaluate_model(knn)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Anomaly TSnE (3d)', 'tsn…

In [41]:
# knn = create_model('knn')
exp_logs = get_logs()

In [42]:
exp_logs

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.TT,params.metric_params,params.p,params.contamination,...,tags.Run Time,tags.Source,tags.URI,tags.mlflow.source.type,tags.mlflow.log-model.history,tags.mlflow.user,tags.USI,tags.Run ID,tags.mlflow.source.name,tags.mlflow.runName
0,993528e295ca472eabcd5e46378ca77a,2,FINISHED,file:///C:/Users/elmha/OneDrive%20-%20Universi...,2022-01-19 17:00:17.436000+00:00,2022-01-19 17:00:17.560000+00:00,0.09,None,2,0.05,...,0.12644481658935547,create_model,63d79a2d,LOCAL,"[{""run_id"": ""993528e295ca472eabcd5e46378ca77a""...",elmha,07d6,993528e295ca472eabcd5e46378ca77a,C:\Users\elmha\AppData\Roaming\Python\Python39...,K-Nearest Neighbors Detector
1,5f3a49811f0f40a49a98978d30f1659e,2,RUNNING,file:///C:/Users/elmha/OneDrive%20-%20Universi...,2022-01-19 17:00:16.861000+00:00,NaT,NaN,None,None,None,...,0.13,setup,3902bde2,LOCAL,None,elmha,07d6,5f3a49811f0f40a49a98978d30f1659e,C:\Users\elmha\AppData\Roaming\Python\Python39...,Session Initialized 07d6
2,5ccb647fc66847b0adb583788932afed,2,FINISHED,file:///C:/Users/elmha/OneDrive%20-%20Universi...,2022-01-19 16:58:49.325000+00:00,2022-01-19 17:00:16.854000+00:00,NaN,None,None,None,...,0.14,setup,6eccddbc,LOCAL,None,elmha,8cc3,5ccb647fc66847b0adb583788932afed,C:\Users\elmha\AppData\Roaming\Python\Python39...,Session Initialized 8cc3

## Nuevos experimentos

In [45]:
from pycaret.classification import *

supervised_new = setup(datas, target = 'etiqueta conjunta', session_id = 123, silent = True, use_gpu = True, create_clusters=True, polynomial_features=False)

In [46]:
# model training and selection
best_supervised_new = compare_models(sort='F1')
# con se_venv

In [47]:
score_grid_best_supervised_new = pull()
score_grid_best_supervised_new

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
catboost,CatBoost Classifier,0.9656,0.9858,0.7757,0.9014,0.8336,0.8146,0.8175,7.499
lightgbm,Light Gradient Boosting Machine,0.9656,0.9845,0.7672,0.9095,0.8320,0.8130,0.8169,1.599
xgboost,Extreme Gradient Boosting,0.9644,0.9854,0.7739,0.8923,0.8286,0.8088,0.8115,0.557
rf,Random Forest Classifier,0.9630,0.9771,0.7525,0.8988,0.8190,0.7986,0.8026,0.726
et,Extra Trees Classifier,0.9614,0.9727,0.7326,0.9017,0.8082,0.7870,0.7924,0.908
dt,Decision Tree Classifier,0.9536,0.8842,0.7942,0.7899,0.7918,0.7657,0.7659,0.063
gbc,Gradient Boosting Classifier,0.9510,0.9621,0.5905,0.9504,0.7280,0.7027,0.7270,1.499
knn,K Neighbors Classifier,0.9341,0.8462,0.5194,0.8239,0.6366,0.6025,0.6221,0.697
ada,Ada Boost Classifier,0.9322,0.8960,0.4467,0.8881,0.5939,0.5613,0.6012,0.507
nb,Naive Bayes,0.9249,0.8267,0.3246,1.0000,0.4894,0.4602,0.5466,0.017
lr,Logistic Regression,0.9247,0.7863,0.3231,1.0000,0.4877,0.4585,0.5453,0.220
ridge,Ridge Classifier,0.9247,0.0000,0.3228,1.0000,0.4873,0.4581,0.5450,0.019
lda,Linear Discriminant Analysis,0.9247,0.8020,0.3228,1.0000,0.4873,0.4581,0.5450,0.037
svm,SVM - Linear Kernel,0.8383,0.0000,0.3844,0.8386,0.4389,0.3891,0.4572,0.263
qda,Quadratic Discriminant Analysis,0.8888,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.022
dummy,Dummy Classifier,0.8888,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.014

In [59]:
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
catboost,CatBoost Classifier,catboost.core.CatBoostClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

In [57]:
score_grid_best_supervised_new.columns

Index(['Model', 'Accuracy', 'AUC', 'Recall', 'Prec.', 'F1', 'Kappa', 'MCC',
       'TT (Sec)'],
      dtype='object')

In [51]:
score_grid_best_supervised_new

AttributeError: 'DataFrame' object has no attribute 'show'

In [55]:
from pycaret.classification import *

supervised_new2 = setup(datas, target = 'etiqueta conjunta', session_id = 123, silent = True, use_gpu = True, create_clusters=False, feature_selection=True)

In [56]:
# model training and selection
best_supervised_new2 = compare_models(sort='F1')
# con se_venv

In [48]:
score_grid_best_supervised_new2 = pull()
score_grid_best_supervised_new2

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
catboost,CatBoost Classifier,0.9656,0.9858,0.7757,0.9014,0.8336,0.8146,0.8175,7.499
lightgbm,Light Gradient Boosting Machine,0.9656,0.9845,0.7672,0.9095,0.8320,0.8130,0.8169,1.599
xgboost,Extreme Gradient Boosting,0.9644,0.9854,0.7739,0.8923,0.8286,0.8088,0.8115,0.557
rf,Random Forest Classifier,0.9630,0.9771,0.7525,0.8988,0.8190,0.7986,0.8026,0.726
et,Extra Trees Classifier,0.9614,0.9727,0.7326,0.9017,0.8082,0.7870,0.7924,0.908
dt,Decision Tree Classifier,0.9536,0.8842,0.7942,0.7899,0.7918,0.7657,0.7659,0.063
gbc,Gradient Boosting Classifier,0.9510,0.9621,0.5905,0.9504,0.7280,0.7027,0.7270,1.499
knn,K Neighbors Classifier,0.9341,0.8462,0.5194,0.8239,0.6366,0.6025,0.6221,0.697
ada,Ada Boost Classifier,0.9322,0.8960,0.4467,0.8881,0.5939,0.5613,0.6012,0.507
nb,Naive Bayes,0.9249,0.8267,0.3246,1.0000,0.4894,0.4602,0.5466,0.017
lr,Logistic Regression,0.9247,0.7863,0.3231,1.0000,0.4877,0.4585,0.5453,0.220
ridge,Ridge Classifier,0.9247,0.0000,0.3228,1.0000,0.4873,0.4581,0.5450,0.019
lda,Linear Discriminant Analysis,0.9247,0.8020,0.3228,1.0000,0.4873,0.4581,0.5450,0.037
svm,SVM - Linear Kernel,0.8383,0.0000,0.3844,0.8386,0.4389,0.3891,0.4572,0.263
qda,Quadratic Discriminant Analysis,0.8888,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.022
dummy,Dummy Classifier,0.8888,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.014

In [65]:
a = [0,1,2]
b = 'letter'
c = {'a':0, 'b':3, 4:4}


d=  (a,b,c)

In [61]:
d[0]

[0, 1, 2]

In [62]:
d[1]

'letter'

In [63]:
d[2]

{'a': 0, 'b': 3}

In [64]:
d[2]['a']

0

In [68]:
d[2][4]

4

In [69]:
best, grid1 , grid2 = d

In [73]:
grid2

{'a': 0, 'b': 3, 4: 4}